export const MAIN_FOOTER_IMG_DATA = [
  {
    id: 1,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 2,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 3,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 4,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 5,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 6,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 7,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 8,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 9,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 10,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
  {
    id: 11,
    thumbnail: './image/itemList/shoesImage/nikeShoes0.jpeg',
    brandName: '남성신발',
    productName: '나이키 리액트 13',
    retailPrice: '13000',
  },
];
