const CONTENTS_MOCK = [
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
  {
    img: './image/itemList/nikeShoes.jpeg',
    itemName: '나이키 리액트 13',
    dragon: '성인 남성 신발',
    type: '운동화',
    colors: '3 컬러',
    discountPrice: 168400,
    originalPrice: 259900,
  },
];

export default CONTENTS_MOCK;
